/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as owlearnCourseSol from "./OwlearnCourse.sol";
export * as owlearnCourse2Sol from "./OwlearnCourse2.sol";
