/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as certificates from "./Certificates";
export * as resources from "./Resources";
export { OwlearnCourse__factory } from "./OwlearnCourse__factory";
export { OwlearnCourseStorage__factory } from "./OwlearnCourseStorage__factory";
