/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as certificates from "./Certificates";
export * as resources from "./Resources";
export { Certificates__factory } from "./Certificates__factory";
export { OwlearnCourse__factory } from "./OwlearnCourse__factory";
