/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OwlearnCourseResources } from "./OwlearnCourseResources";
export type { OwlearnCourseResourcesStorage } from "./OwlearnCourseResourcesStorage";
