/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OwlearnCourseResources__factory } from "./OwlearnCourseResources__factory";
export { OwlearnCourseResourcesStorage__factory } from "./OwlearnCourseResourcesStorage__factory";
