/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as certificates from "./Certificates";
export type { certificates };
import type * as resources from "./Resources";
export type { resources };
export type { Certificates } from "./Certificates";
export type { OwlearnCourse } from "./OwlearnCourse";
