/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as courseFactorySol from "./CourseFactory.sol";
export { CourseFactoryStorage__factory } from "./CourseFactoryStorage__factory";
