/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as owlearnCourseCerticatesStorageSol from "./OwlearnCourseCerticatesStorage.sol";
export type { owlearnCourseCerticatesStorageSol };
export type { OwlearnCourseCertificates } from "./OwlearnCourseCertificates";
