/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as owlearnCourseCertificatesSol from "./OwlearnCourseCertificates.sol";
export type { owlearnCourseCertificatesSol };
