/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as owlearnCourseCerticatesStorageSol from "./OwlearnCourseCerticatesStorage.sol";
export { OwlearnCourseCertificates__factory } from "./OwlearnCourseCertificates__factory";
