/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as educatorBadge from "./EducatorBadge";
export * as factory from "./Factory";
export * as implementation from "./Implementation";
export * as owlearnCourse from "./OwlearnCourse";
export * as owlearnId from "./OwlearnId";
export * as proxy from "./Proxy";
export * as extras from "./extras";
export * as interfaces from "./interfaces";
export * as modules from "./modules";
