/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OwlearnId__factory } from "./OwlearnId__factory";
export { OwlearnIdStorage__factory } from "./OwlearnIdStorage__factory";
