/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as courseFactorySol from "./CourseFactory.sol";
export type { courseFactorySol };
export type { CourseFactoryStorage } from "./CourseFactoryStorage";
