/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC721A__IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721A__IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC721A",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721A__factory>;
    getContractFactory(
      name: "IERC721A",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721A__factory>;
    getContractFactory(
      name: "OwnableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableUpgradeable__factory>;
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "ERC721Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Upgradeable__factory>;
    getContractFactory(
      name: "IERC721MetadataUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721MetadataUpgradeable__factory>;
    getContractFactory(
      name: "IERC721ReceiverUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721ReceiverUpgradeable__factory>;
    getContractFactory(
      name: "IERC721Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Upgradeable__factory>;
    getContractFactory(
      name: "ContextUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ContextUpgradeable__factory>;
    getContractFactory(
      name: "ERC165Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165Upgradeable__factory>;
    getContractFactory(
      name: "IERC165Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165Upgradeable__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC4906",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC4906__factory>;
    getContractFactory(
      name: "ERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155__factory>;
    getContractFactory(
      name: "ERC1155Burnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155Burnable__factory>;
    getContractFactory(
      name: "ERC1155Supply",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155Supply__factory>;
    getContractFactory(
      name: "ERC1155URIStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155URIStorage__factory>;
    getContractFactory(
      name: "IERC1155MetadataURI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155MetadataURI__factory>;
    getContractFactory(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155__factory>;
    getContractFactory(
      name: "IERC1155Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Receiver__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "ERC721Burnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Burnable__factory>;
    getContractFactory(
      name: "ERC721URIStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721URIStorage__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "OwlearnEducatorBadge",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwlearnEducatorBadge__factory>;
    getContractFactory(
      name: "OwlearnCourseResource",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwlearnCourseResource__factory>;
    getContractFactory(
      name: "OwlearnCourseResource",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwlearnCourseResource__factory>;
    getContractFactory(
      name: "OwlearnCourseFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwlearnCourseFactory__factory>;
    getContractFactory(
      name: "IMintModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMintModule__factory>;
    getContractFactory(
      name: "IOwlearnId",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOwlearnId__factory>;
    getContractFactory(
      name: "OwlearnModuleBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwlearnModuleBase__factory>;
    getContractFactory(
      name: "Certificates",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Certificates__factory>;
    getContractFactory(
      name: "OwlearnCourseCerticates",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwlearnCourseCerticates__factory>;
    getContractFactory(
      name: "OwlearnCourse",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwlearnCourse__factory>;
    getContractFactory(
      name: "OwlearnCourseResources",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwlearnCourseResources__factory>;
    getContractFactory(
      name: "OwlearnId",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwlearnId__factory>;
    getContractFactory(
      name: "OwlearnId",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwlearnId__factory>;
    getContractFactory(
      name: "OwlearnIdStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwlearnIdStorage__factory>;
    getContractFactory(
      name: "OwlearnIdStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwlearnIdStorage__factory>;

    getContractAt(
      name: "ERC721A__IERC721Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721A__IERC721Receiver>;
    getContractAt(
      name: "ERC721A",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721A>;
    getContractAt(
      name: "IERC721A",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721A>;
    getContractAt(
      name: "OwnableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnableUpgradeable>;
    getContractAt(
      name: "Initializable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "ERC721Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Upgradeable>;
    getContractAt(
      name: "IERC721MetadataUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721MetadataUpgradeable>;
    getContractAt(
      name: "IERC721ReceiverUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721ReceiverUpgradeable>;
    getContractAt(
      name: "IERC721Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Upgradeable>;
    getContractAt(
      name: "ContextUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ContextUpgradeable>;
    getContractAt(
      name: "ERC165Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165Upgradeable>;
    getContractAt(
      name: "IERC165Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165Upgradeable>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC4906",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC4906>;
    getContractAt(
      name: "ERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155>;
    getContractAt(
      name: "ERC1155Burnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155Burnable>;
    getContractAt(
      name: "ERC1155Supply",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155Supply>;
    getContractAt(
      name: "ERC1155URIStorage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155URIStorage>;
    getContractAt(
      name: "IERC1155MetadataURI",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155MetadataURI>;
    getContractAt(
      name: "IERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155>;
    getContractAt(
      name: "IERC1155Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Receiver>;
    getContractAt(
      name: "ERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "ERC721Burnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Burnable>;
    getContractAt(
      name: "ERC721URIStorage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721URIStorage>;
    getContractAt(
      name: "IERC721Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "OwlearnEducatorBadge",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwlearnEducatorBadge>;
    getContractAt(
      name: "OwlearnCourseResource",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwlearnCourseResource>;
    getContractAt(
      name: "OwlearnCourseResource",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwlearnCourseResource>;
    getContractAt(
      name: "OwlearnCourseFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwlearnCourseFactory>;
    getContractAt(
      name: "IMintModule",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMintModule>;
    getContractAt(
      name: "IOwlearnId",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IOwlearnId>;
    getContractAt(
      name: "OwlearnModuleBase",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwlearnModuleBase>;
    getContractAt(
      name: "Certificates",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Certificates>;
    getContractAt(
      name: "OwlearnCourseCerticates",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwlearnCourseCerticates>;
    getContractAt(
      name: "OwlearnCourse",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwlearnCourse>;
    getContractAt(
      name: "OwlearnCourseResources",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwlearnCourseResources>;
    getContractAt(
      name: "OwlearnId",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwlearnId>;
    getContractAt(
      name: "OwlearnId",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwlearnId>;
    getContractAt(
      name: "OwlearnIdStorage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwlearnIdStorage>;
    getContractAt(
      name: "OwlearnIdStorage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwlearnIdStorage>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
