/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as educatorBadge from "./EducatorBadge";
export type { educatorBadge };
import type * as factory from "./Factory";
export type { factory };
import type * as owlearnCourse from "./OwlearnCourse";
export type { owlearnCourse };
import type * as owlearnId from "./OwlearnId";
export type { owlearnId };
import type * as extras from "./extras";
export type { extras };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as modules from "./modules";
export type { modules };
import type * as storage from "./storage";
export type { storage };
export type { OwlearnId } from "./OwlearnId";
