/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as owlearnCourseSol from "./OwlearnCourse.sol";
export type { owlearnCourseSol };
import type * as owlearnCourse2Sol from "./OwlearnCourse2.sol";
export type { owlearnCourse2Sol };
export type { FeeToken } from "./FeeToken";
